// <auto-generated />
using System;
using EF_1.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_1.Migrations
{
    [DbContext(typeof(ITIcontext))]
    [Migration("20240817124231_fixIssus")]
    partial class fixIssus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_1.Entites.Coreses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("EF_1.Entites.Crsins", b =>
                {
                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<int>("CoresesId")
                        .HasColumnType("int");

                    b.Property<int?>("CoresesId1")
                        .HasColumnType("int");

                    b.Property<int>("evaluate")
                        .HasColumnType("int");

                    b.HasKey("InstructorId", "CoresesId");

                    b.HasIndex("CoresesId");

                    b.HasIndex("CoresesId1");

                    b.ToTable("Crsins");
                });

            modelBuilder.Entity("EF_1.Entites.Dept", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Hiredate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("depts");
                });

            modelBuilder.Entity("EF_1.Entites.Instructor", b =>
                {
                    b.Property<int>("InstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructorId"));

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InstructorId");

                    b.HasIndex("DeptId");

                    b.ToTable("Instructors");
                });

            modelBuilder.Entity("EF_1.Entites.Stdcrs", b =>
                {
                    b.Property<int>("Studentid")
                        .HasColumnType("int");

                    b.Property<int>("Coreseid")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Studentid", "Coreseid");

                    b.HasIndex("Coreseid");

                    b.HasIndex("StudentId");

                    b.ToTable("stdcrs");
                });

            modelBuilder.Entity("EF_1.Entites.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("DeptId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeptId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EF_1.Entites.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Topics");
                });

            modelBuilder.Entity("EF_1.Entites.Coreses", b =>
                {
                    b.HasOne("EF_1.Entites.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("EF_1.Entites.Crsins", b =>
                {
                    b.HasOne("EF_1.Entites.Coreses", "coreses")
                        .WithMany()
                        .HasForeignKey("CoresesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_1.Entites.Coreses", null)
                        .WithMany("Crsins")
                        .HasForeignKey("CoresesId1");

                    b.HasOne("EF_1.Entites.Instructor", "Instructor")
                        .WithMany("Crsins")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");

                    b.Navigation("coreses");
                });

            modelBuilder.Entity("EF_1.Entites.Dept", b =>
                {
                    b.HasOne("EF_1.Entites.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EF_1.Entites.Instructor", b =>
                {
                    b.HasOne("EF_1.Entites.Dept", "Dept")
                        .WithMany("Instructors")
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("EF_1.Entites.Stdcrs", b =>
                {
                    b.HasOne("EF_1.Entites.Coreses", "Corese")
                        .WithMany("Stdcrs")
                        .HasForeignKey("Coreseid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EF_1.Entites.Student", null)
                        .WithMany("Stdcrs")
                        .HasForeignKey("StudentId");

                    b.HasOne("EF_1.Entites.Student", "Student")
                        .WithMany()
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corese");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EF_1.Entites.Student", b =>
                {
                    b.HasOne("EF_1.Entites.Dept", "Dept")
                        .WithMany()
                        .HasForeignKey("DeptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dept");
                });

            modelBuilder.Entity("EF_1.Entites.Coreses", b =>
                {
                    b.Navigation("Crsins");

                    b.Navigation("Stdcrs");
                });

            modelBuilder.Entity("EF_1.Entites.Dept", b =>
                {
                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("EF_1.Entites.Instructor", b =>
                {
                    b.Navigation("Crsins");
                });

            modelBuilder.Entity("EF_1.Entites.Student", b =>
                {
                    b.Navigation("Stdcrs");
                });
#pragma warning restore 612, 618
        }
    }
}
